// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace EcomerenceSugestionModel
{
    public partial class MLModel1
    {
        /// <summary>
        /// model input class for MLModel1.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"Id")]
            public string Id { get; set; }

            [ColumnName(@"ProductId")]
            public string ProductId { get; set; }

            [ColumnName(@"ProducerName")]
            public string ProducerName { get; set; }

            [ColumnName(@"Amount")]
            public float Amount { get; set; }

            [ColumnName(@"Price")]
            public float Price { get; set; }

            [ColumnName(@"UserId")]
            public string UserId { get; set; }

            [ColumnName(@"Bought")]
            public float Bought { get; set; }

            [ColumnName(@"BrandTag")]
            public float BrandTag { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLModel1.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"Id")]
            public string Id { get; set; }

            [ColumnName(@"ProductId")]
            public uint ProductId { get; set; }

            [ColumnName(@"ProducerName")]
            public string ProducerName { get; set; }

            [ColumnName(@"Amount")]
            public float Amount { get; set; }

            [ColumnName(@"Price")]
            public float Price { get; set; }

            [ColumnName(@"UserId")]
            public uint UserId { get; set; }

            [ColumnName(@"Bought")]
            public float Bought { get; set; }

            [ColumnName(@"BrandTag")]
            public float BrandTag { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("MLModel1.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
